name: 'Thank You Action'
description: 'Say "Thank You" to new pull requests'
author: 'Muzammal Nazir'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'