name: 'Thank You Action'
description: 'Say "Thank You" to new pull requests'
author: 'Muzammal Nazir'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  buildArgs:
    description: 'Json object'
    required: false
    default: "{}"
  deployArgs:
    description: 'Json object'
    required: false
    default: "{}"

runs:
  using: 'node12'
  main: 'dist/index.js'